Repository tgstation/rust-g, pull requests merged in 2022-07, with the labels that each got.

#98 toml to json now returns error reasons to byond + rust-analyzer.cargo.target gnu > msvc
  .vscode/settings.json
  README.md
  dmsrc/toml.dm
  src/toml.rs
  tests/abc-tests.rs
  tests/dm/toml.dme
Labels: Fix

#105 Small improvements for before 1.0
  .github/workflows/rust.yml
  Cargo.lock
  LICENSE
  README.md
Labels: GitHub

#106 1.0.0
  Cargo.lock
  Cargo.toml
Labels: enhancement

#107 Pallette Encoding Image Fix
  Cargo.toml
  src/dmi.rs
Labels: bug

#108 Uploads rust_g.dm as an Actions Artifact
  .github/workflows/rust.yml
Labels: GitHub

#112 Returns the TOML library to previous functionality
  dmsrc/toml.dm
  tests/dm/toml.dme
Labels: bug, Fix
